"use client";

import type { AdminResourcePayloads } from "@/lib/api/schemas";
import type { ApiResource } from "@/types/broka";

const value = (item: unknown) => item === null || item === undefined || item === "" ? "—" : String(item);
const date = (item: string | null) => item ? new Date(item).toLocaleString("en-KE") : "—";
function Metric({ label, value: item }: { label: string; value: unknown }) { return <div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-600">{label}</p><p className="mt-2 text-lg font-semibold text-slate-200">{value(item)}</p></div>; }

export function ValidatedResourceView({ resource, data }: { resource: ApiResource; data: unknown }) {
  if (resource === "fraudEvents") { const rows = data as AdminResourcePayloads["fraudEvents"]; return <div className="divide-y divide-white/[0.06]">{rows.map((row) => <div key={row.id} className="grid gap-3 px-4 py-4 sm:grid-cols-[1fr_1.5fr_120px_120px_180px]"><div><p className="text-sm font-semibold text-slate-100">{row.user_id}</p><p className="text-xs text-slate-500">{row.id}</p></div><p className="text-sm text-slate-300">{row.reason}</p><p className="text-sm text-slate-300">{row.trust_score_at_flag}</p><p className="text-sm text-slate-300">{row.resolved ? "Resolved" : "Open"}</p><p className="text-xs text-slate-500">{date(row.created_at)}</p></div>)}</div>; }
  if (resource === "transactions") { const rows = data as AdminResourcePayloads["transactions"]; return <div className="divide-y divide-white/[0.06]">{rows.map((row) => <div key={row.id} className="grid gap-3 px-4 py-4 sm:grid-cols-[1fr_1fr_120px_120px_1.2fr]"><div><p className="text-sm font-semibold text-slate-100">{row.id}</p><p className="text-xs text-slate-500">Deal {row.deal_id}</p></div><p className="text-sm text-slate-300">KES {row.amount.toLocaleString()}</p><p className="text-sm text-slate-300">{row.status}</p><p className="text-sm text-slate-300">{row.mpesa_receipt ?? "—"}</p><p className="text-xs text-slate-500">Buyer {row.buyer_id} · {date(row.created_at)}</p></div>)}</div>; }
  if (resource === "auditLogs") { const rows = data as AdminResourcePayloads["auditLogs"]; return <div className="divide-y divide-white/[0.06]">{rows.map((row) => <div key={row.id} className="grid gap-3 px-4 py-4 sm:grid-cols-[180px_1fr_1fr_1.5fr]"><p className="text-xs text-slate-500">{date(row.created_at)}</p><div><p className="text-sm font-semibold text-slate-200">{row.action}</p><p className="text-xs text-slate-500">Actor {row.actor_id}</p></div><p className="text-sm text-slate-300">{row.resource_type}/{row.resource_id}</p><p className="text-xs leading-5 text-slate-400">{row.detail || "No detail"}</p></div>)}</div>; }
  if (resource === "aiSavings") { const row = data as AdminResourcePayloads["aiSavings"]; return <div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Prefilter avoided" value={row.classification_calls_avoided_by_prefilter} /><Metric label="Cache avoided" value={row.classification_calls_avoided_by_cache} /><Metric label="Calls made" value={row.classification_calls_made} /><Metric label="Requests" value={row.classification_requests_total} /><Metric label="Avoided fraction" value={`${(row.avoided_fraction * 100).toFixed(2)}%`} /></div>; }
  if (resource === "ledgerIntegrity") { const row = data as AdminResourcePayloads["ledgerIntegrity"]; return <div className="space-y-4 p-4"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Credits" value={`KES ${row.total_credits_kes.toLocaleString()}`} /><Metric label="Debits" value={`KES ${row.total_debits_kes.toLocaleString()}`} /><Metric label="Discrepancy" value={`KES ${row.discrepancy_kes.toLocaleString()}`} /></div><p className={row.escrow_integrity_ok ? "text-sm text-emerald-200" : "text-sm text-rose-200"}>{row.escrow_integrity_ok ? "Escrow integrity check passed." : `${row.negative_escrow_deals.length} negative escrow balance(s) require attention.`}</p></div>; }
  if (resource === "eventMetrics") { const row = data as AdminResourcePayloads["eventMetrics"]; return <div className="space-y-4 p-4"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Events since restart" value={row.total_events} /><Metric label="Registered handlers" value={row.registered_handlers} /><Metric label="Event types observed" value={Object.keys(row.by_type).length} /></div><div className="flex flex-wrap gap-2">{Object.entries(row.by_type).map(([key, count]) => <span key={key} className="rounded-full border border-white/[0.07] px-3 py-1 text-xs text-slate-400">{key}: {count}</span>)}</div></div>; }
  if (resource === "eventCatalog") { const row = data as AdminResourcePayloads["eventCatalog"]; return <div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(row.by_domain).map(([domain, events]) => <div key={domain} className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><p className="text-sm font-semibold text-slate-200">{domain}</p><p className="mt-2 text-xs leading-5 text-slate-500">{events.join(" · ")}</p></div>)}</div>; }
  if (resource === "workflowVersions") { const row = data as AdminResourcePayloads["workflowVersions"]; return <div className="p-4"><Metric label="Current workflow version" value={row.current_version} /><pre className="mt-4 max-h-72 overflow-auto rounded-xl bg-black/20 p-4 text-xs text-slate-400">{JSON.stringify(row.versions, null, 2)}</pre></div>; }
  if (resource === "econfirmDiagnostics") { const row = data as AdminResourcePayloads["econfirmDiagnostics"]; return <div className="grid gap-3 p-4 sm:grid-cols-2"><Metric label="Configured" value={row.configured ? "Yes" : "No"} /><Metric label="Call" value={row.call} /><Metric label="Result" value={row.ok ? "OK" : row.error ?? "Failed"} /><Metric label="Message" value={row.message ?? "—"} /></div>; }
  if (resource === "clientIpDiagnostics") { const row = data as AdminResourcePayloads["clientIpDiagnostics"]; return <div className="grid gap-3 p-4 sm:grid-cols-2"><Metric label="Resolved address" value={row.resolved} /><Metric label="Source" value={row.source} /><Metric label="Peer" value={row.peer} /><Metric label="Trusted proxy hops" value={row.config.trusted_proxy_hops} /></div>; }
  return null;
}
